### ISSUE TITLE
Unable to migrate diff.

### ISSUE THREAD

**Issue by Ricknox** [doctrine/DoctrineMigrationsBundle#187]
When executing `php bin/console doctrine:migrations:migrate` the following exception will be thrown:

>  [Symfony\Component\Debug\Exception\ContextErrorException]
>  Warning: mkdir(): File exists

Debugging this error results in the following exception trace:

>  [Symfony\Component\Debug\Exception\ContextErrorException]
>  Warning: mkdir(): File exists

```shell
Exception trace:
 () at C:\Users\Ricardo\Documents\doctrinetest\vendor\doctrine\doctrine-migrations-bundle\Command\DoctrineCommand.php:35
 Doctrine\Bundle\MigrationsBundle\Command\DoctrineCommand::configureMigrations() at C:\Users\Ricardo\Documents\doctrinetest\vendor\doctrine\doctrine-migrations-bundle\Command\MigrationsMigrateDoctrineCommand.php:53
 Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() at C:\Users\Ricardo\Documents\doctrinetest\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:255
 Symfony\Component\Console\Command\Command->run() at C:\Users\Ricardo\Documents\doctrinetest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at C:\Users\Ricardo\Documents\doctrinetest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:191
 Symfony\Component\Console\Application->doRun() at C:\Users\Ricardo\Documents\doctrinetest\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\Users\Ricardo\Documents\doctrinetest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:122
 Symfony\Component\Console\Application->run() at C:\Users\Ricardo\Documents\doctrinetest\bin\console:23
```

Could this be fixed? Has this error something to do with PR #169?

**Comment by mikeSimonson** [comment]
@Ricknox Can you confirm that your problem is fixed on master ?

**Comment by Ricknox** [comment]
@mikeSimonson Unfortunately that did not fix the problem. I am still getting the same exception. Is there some other information or configuration you'd like to see?

**Comment by Ricknox** [comment]
@mikeSimonson Yes, that fixes the error. Feel free to close this issue when you released a new stable version.

**Comment by Ricknox** [comment]
Released new version. Closing this issue. Thank you for the pull request.
