### ISSUE TITLE
Multiple entity managers support

### ISSUE THREAD

**Issue by dinamic** [doctrine/DoctrineMigrationsBundle#38]
Inside our ERP system we have calls to multiple database storages. To use them with Symfony2, we've defined them as different connections each one attached to a different entity manager.

If we make some change to the database structure there is no way to specify on which entity manager this change is going to be performed.

This can be controlled via the command line, but doing so is not reliable, unless we cherry-pick the doctrine migrations on deployment and specify different "--em" argument depending on the current migration.

**Comment by richsage** [comment]
+1

**Comment by zodeus** [comment]
+1

**Comment by hasumedic** [comment]
+1

**Comment by suncat2000** [comment]
Awesome!

**Comment by hason** [comment]
+1

**Comment by aclarkd** [comment]
+1

**Comment by odino** [comment]
+1

**Comment by kingcrunch** [comment]
:+1: 

But seriously: What happened to this ticket?

**Comment by dinamic** [comment]
Two years later nothing has changed.

I am still going to recommend the [Container Aware Migrations](https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/Resources/doc/index.rst#container-aware-migrations) as a workaround.

**Comment by Max101** [comment]
:thumbsup: +1 
Hope to see this someday...

**Comment by ryall** [comment]
+1

**Comment by pasmaill** [comment]
+1

**Comment by eggyal** [comment]
+1

**Comment by sp-enric-fradera** [comment]
A few downsides I found to the proposed container workaround:
- It's ugly as hell.
- You get a console warning for not executing any SQL.
- The queries get executed even if you do a dry-run.

**Comment by spinx** [comment]
@stof 
We have a fork where we added support for this. Kinda necessary with 16 EMs on the app. 

Couple of things:
- we need to track the em migration was executed against like so http://i.imgur.com/aAhHfuh.png
- changes to doctrine/migrations are necessary

If we clean the code up a bit would you be in a position to merge a PR in on both this repo and doctrine/migrations ?

**Comment by stof** [comment]
@spinx does it really need a change in doctrine/migrations itself ? what kind of change ?

**Comment by spinx** [comment]
@stof Mostly changes to commands. To allow diffing on all EMs, generating migrations for EMs. As I mentioned the only downside is that you need to track which EM the migration is for so you need to append EM name or similar to the migration version.

**Comment by mikeSimonson** [comment]
@spinx or you just use different configuration for different em and your problem is already solved.

**Comment by spinx** [comment]
@mikeSimonson I'm not sure I understand what you mean by that. Can you elaborate ?

**Comment by mikeSimonson** [comment]
For each migration command you can pass an entity manager and a migration configuration.
In the migration configuration you can set the migration folder and the sql table that will hold the version migrated.
Then you create an em configuration for all your different em.

The result will be that the migration on your different em are going to be independent of each other.

**Comment by spinx** [comment]
Ah, I see. Might be a way to go, not sure. 

@stof Is adding em to migration version acceptable ? Or maybe a column of 'manager' that defaults to 'default' instead, to have more backwards compatibility. People are probably relying on versions to be integers, right?

**Comment by mikeSimonson** [comment]
That would be a huge BC break and honestly you shouldn't use the em for migrations in the first place.
It's only going to bring you performance issues and troubles.

**Comment by spinx** [comment]
Wouldn't use the EM but you somehow need to know against which EM you want to execute. Also if you are diffing to generate migrations files, the way it works now, having unix time as version, you can't really generate migrations for multiple EMs. Well you can do sleep(1) which is a bas solution as well.

**Comment by mikeSimonson** [comment]
You don't need to know against which em you are executing the migrations and there are no collision possible for the migrations version name as they are completely separate in different configurations / folders.

**Comment by spinx** [comment]
ok, so just add support for multiple dirs here:
https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/DependencyInjection/Configuration.php#L39

and update code to process that correctly ? 

that might work, what I like about our solution though is that it doesn't need any configuration.

**Comment by mikeSimonson** [comment]
The difference between you solution and mine is that in yours you need to hardcode that multiple folder logic in the code and add a million of tests to account for all the weird edge cases that your are going to hit.
In mine it works now with the current code and you won't have any surprise because 2 migrations in 2 differents folders have the same name and collision in the migration_versions table.

**Comment by dinamic** [comment]
IMO the most elegant solution would be to be able to provide migration configuration within the migration itself. This way you will be able to select entity manager or connection to execute the migration towards. Also we will have the flexibility of adding new features in the future without too much hassle.

Thoughts?

**Comment by stof** [comment]
@dinamic this does not make sense. the configuration is responsible for finding migrations, so the migration cannot be providing a configuration.

There should be strictly nothing to change in the library for that, as it is perfectly logical for a migration configuration to operate on a single connection.
Supporting multiple configuration because of a multi-em setup should be a job for the bundle only, and its proxied command settin gthe appropriate helper will be the place to switch between entity managers (as done in DoctrineBundle)

**Comment by spinx** [comment]
ok, I'll play around a bit keeping in mind your feedback and try to find an elegant solution

**Comment by mikeSimonson** [comment]
@spinx I want to re add that using the em in the first place is a bad idea (unless you have to support multiple databases). You will have issues when you change an entity and you will have an super slow migration.

In general you should only use plain sql.

**Comment by flohw** [comment]
Solution proposed by @mikeSimonson works very well. Maybe we can find something easier to use but in my opinion the feature is already here.

**Comment by succinct** [comment]
I've run into the same problem. I did find that I can specify `--db=<database_name>` to run only the ones that are tied to that DB - but then it tries to run them against the default EM, and you can't specify both `--em` and `--db` at the same time.

**Comment by angelsk** [comment]
Yup, DB option finally ran the correct migration - but into the wrong DB :(

**Comment by idchlife** [comment]
So, is there working solution?

**Comment by andrzejdziekonski** [comment]
My workaround was: 
- add prefix to the 2nd connection tables
- in the 1st connection configuration adding schema_filter exluding above prefix
- in the migration class where i modify prefix tables i add skipIf confition on the database name to be sure that the migration goes for correct db (you can use ContainerAwareInterface to grab dbname from parameters) 
- then i execute up for above migration with --em parameter

Result is that i can use two em's and migrating databases with no issues. As the 2nd db won't change ofter (if ever) i am kinda satisfied with that ignore filter solution.

**Comment by timiTao** [comment]
👎 after few years, still no good official solution?

**Comment by stevechilds** [comment]
There are some really glaring omissions with Symfony & Doctrine and this is one of them. Unbelievable that this hasn't been addressed by now, over 4 years since it was first logged.

We use multiple entity managers to talk to different databases, without this we basically can't use migrations without hacking the source.

**Comment by spinx** [comment]
We have our own wrapper commands that do diffs and migrations across 25 entity managers, and it works great. Our solution generates migration files in separate directories, which is fine for us, because each bundle has its own migrations dir. I agree this is not a good approach for everyone. 

I'm still willing to work on this but we need to agree on an approach. 

Ability to use multiple databases seems so basic to me, even small projects have more than one database in our case. Why is this not wanted @stof @mikeSimonson ?

**Comment by Wirone** [comment]
I, too, can't believe this is not resolved. Like Doctrine's ORM configuration can have multiple entity managers set and each manager can have its own database connection, DoctrineMigrationBundle's config should support multiple entity managers in order to migrate different databases. This is so natural and basic for me - it's unbelievable that it's not possible.

**Comment by landsman** [comment]
please :)

**Comment by ndench** [comment]
I was able to get it working using multiple configuration files, as specified by one of the answers on [this question](https://stackoverflow.com/q/6844153/1393498). I just have to make sure I specify `--configuration` and `--em` everytime I run the migrations.

**Comment by landsman** [comment]
please :)

**Comment by raitocz** [comment]
This is unbelievable issue and should be solved a long time ago. It is even encouraged in official documentation of Symfony.

**Comment by alcaeus** [comment]
Please refrain from adding further comments asking for this to be implemented or commenting how this should've been done already: I'd really hate to have to lock this issue to prevent such spam.

Instead, everyone that needs this may instead come up with suggestions how they'd like this functionality to behave or even take a stab at implementing it. Thank you for understanding.

**Comment by dvc** [comment]
Hello everybody!

I have two different databases: legacy MariaDb and new PostgreSQL. Entities for this databases stored in different subfolders: src/Entity/{Legacy,Default}.

I can use different entity managers in my migrations, but i can't use different directories and namespaces for them. 
Using parameter `--config` looks unfriendly. Can you support alternatives for configuration tree builder? Something like:

```yaml
# simple config
doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migrations'
    namespace: DoctrineMigrations
```

and 

```yaml
# multiply
doctrine_migrations:
  - entity_manager: default
    dir_name: '%kernel.project_dir%/src/Migrations/Default'
    namespace: DoctrineMigrationsDefault
   ...
  - entity_manager: legacy
    dir_name: '%kernel.project_dir%/src/Migrations/Legacy'
    namespace: DoctrineMigrationsLegacy
    ...
```

No command usage differences expected:

```
# use default entity manager
doctrine:migration:diff
or
doctrine:migration:diff --em=default
```

```
# use legacy entity manager
doctrine:migration:diff --em=legacy
```

**Comment by SchmidtClaudia** [comment]
I would suggest an connection option for the commands and an configuration that is based on the doctrine configuration for multiple entity managers and also uses their mapping, so basically doctrine_migrations.yaml needs the following changes
```
doctrine_migrations:
    default_connection: default
    connections:
        default:
            migrations_paths:
                'App\Migrations\Main': 'src/Migrations/Main'
        customer:
            migrations_paths:
                'App\Migrations\Customer': 'src/Migrations/Customer'
```

doctrine.yaml: https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

Trying to implement this but no promise yet

**Comment by devnix** [comment]
I'm still testing a few things. It is a very nasty way to overcome the problem, and I know that a good part of the code is not optimal at all, specially `DoctrineMigrationsMultipleDatabaseExtension::loadEntityManagerConfiguration()`, but **any feedback is very welcome**: https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle

It proposes a similar configuration like @SchmidtClaudia's but without a `default_connection`. My bundle would iterate over every entity manager defined into your configuration, and you can filter it to run migrations for one entity manager just adding a `--em=example` option to each command.

I don't know if it can help someone to inspire a PR to DoctrineMigrationsBundle repository, I think that should be the end of the road, and not hacking it since 2012.

**Comment by kolyadin** [comment]
Any good modern solution to handle this problem?

**Comment by devnix** [comment]
@kolyadin We have been using the bundle from my previous comment since I've published it in production at my job without problems. You can give it a try and provide any feedback. But as you requested, the good solution would be to get this functionality on DoctrineMigrationsBundle.

**Comment by mattsbennett** [comment]
I was using the `ContainerAwareInterface` approach, but now upgrading to Symfony 4/DoctrineMigrationsBundle 3 and it no longer seems feasible. What is the typical approach to deal with migrations for multiple entity managers now? I've got several separate different entity managers/dbs - how do I apply migrations only to the correct em/db now?

**Comment by ndench** [comment]
The approach I mentioned above https://github.com/doctrine/DoctrineMigrationsBundle/issues/38#issuecomment-405811040 is still working for me with symfony 5 and doctrine migrations 3. It does require running the migration command once for every entity manager, but I just put it a makefile and it's easy enough.

**Comment by mattsbennett** [comment]
@ndench thanks, that's good to know - what versions of `doctrine/migrations`, `doctrine/doctrine-migrations-bundle` are you using? I tried the approach in that post/answer and the configuration keys weren't recognized on the latest:

```
        "doctrine/doctrine-migrations-bundle": "3.2.2",
        "doctrine/migrations": "3.5.0",
```

**Comment by ndench** [comment]
I've got the following versions:

```
doctrine/migrations                          3.4.1                          
doctrine/doctrine-migrations-bundle          3.2.2                          
```

However, you're right. I forgot that I updated the configuration.  It still follows the same principle though. I have two migrations config files:

```yaml
# config/packages/migrations/base.yaml
em: default
transactional: false
migrations_paths:
    Hyra\Migrations\Base: src/Migrations/Base
table_storage:
    table_name: migration_versions
```

```yaml
# config/packages/migrations/special.yaml
em: special
transactional: false
migrations_paths:
    App\Migrations\Special: src/Migrations/Special
table_storage:
    table_name: migration_versions
```

And then I have these in my Makefile so that I don't need to remember the magic incantations:
```
migrate: migrate-base migrate-special

migrate-base:
	php bin/console doctrine:migrations:migrate --configuration=config/packages/migrations/base.yaml --no-interaction --allow-no-migration

migrate-special:
	php bin/console doctrine:migrations:migrate --configuration=config/packages/migrations/special.yaml --no-interaction --allow-no-migration

diff-migrations-base: migrate
	php bin/console doctrine:migrations:diff --configuration=config/packages/migrations/base.yaml

diff-migrations-special: migrate
	php bin/console doctrine:migrations:diff --configuration=config/packages/migrations/special.yaml
```

Hope that helps!

**Comment by mattsbennett** [comment]
@ndench thanks so much for getting back to me, that helped my isolate my issue.

I need to inject services into my migration classes via `Doctrine\Migrations\Version\MigrationFactory`, so I need to use the root level `config/packages/doctrine_migrations.yaml` configuration for its `services` configuration.

A configuration file with this key can't be passed via `--configuration`, I believe because `services` is a feature of the bundle, not `doctrine/migrations`.

And, when I _do_ include that file, even with just the `services` config, the passed separate `--configuration` file is ignored.

So, we're going to try implementing our own command wrapper I guess. Edit: Ended up getting [DoctrineMigrationsMultipleDatabaseBundle](https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle) working, which is a simpler approach for our needs (thanks for this @devnix 🙌 ).

**Comment by jgauthi** [comment]
The repository [DoctrineMigrationsMultipleDatabaseBundle](https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle) is archived, an official version would be appreciated _(I don't have the skills to do it)_.

**Comment by kraz** [comment]
As an alternative to [DoctrineMigrationsMultipleDatabaseBundle](https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle) I created the [Doctrine Context Bundle](https://github.com/kraz/doctrine-context-bundle) which uses similar approach.

Hope it's useful to someone, as it's for me.
